<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="arcus" params="prefix">

  <!-- Constants -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="4.0" />
  <xacro:property name="base_width" value="0.13" />
  <xacro:property name="base_length" value="0.345" />
  <xacro:property name="base_height" value="0.070" />
  <xacro:property name="wheelbase" value="0.255" />
  <xacro:property name="wheel_mass" value="0.34055" />
  <xacro:property name="wheel_len" value="0.03" />
  <xacro:property name="wheel_radius" value="0.04" />

  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>

  <material name="orange">
    <color rgba="1 0.47 0 1"/>
  </material>

  <!-- Base and chassis -->
  <link name="${prefix}base_link" />

  <link name="${prefix}chassis_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
  </link>

  <joint name="${prefix}chassis_joint" type="fixed">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}chassis_link"/>
    <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
    <dynamics damping="0.2"/>
  </joint>

  <!-- Rear Left Wheel (Driven) -->
  <link name="${prefix}rear_left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="${prefix}rear_left_wheel_joint" type="continuous">
    <parent link="${prefix}chassis_link"/>
    <child link="${prefix}rear_left_wheel"/>
    <origin xyz="-${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- Rear Right Wheel -->
  <link name="${prefix}rear_right_wheel">
    <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="orange"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
  </link>

  <joint name="${prefix}rear_right_wheel_joint" type="continuous">
    <parent link="${prefix}chassis_link"/>
    <child link="${prefix}rear_right_wheel"/>
    <origin xyz="-${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- Front Left Steering Link -->
  <link name="${prefix}front_left_steering_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/> <!-- Small mass for steering link -->
      <inertia
        ixx="1e-5" ixy="0.0" ixz="0.0"
        iyy="1e-5" iyz="0.0"
        izz="1e-5"/>
    </inertial>
  </link>
  <joint name="${prefix}front_left_steering_joint" type="revolute">
    <parent link="${prefix}chassis_link"/>
    <child link="${prefix}front_left_steering_link"/>
    <origin xyz="${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
  </joint>

  <!-- Front Left Wheel -->
  <link name="${prefix}front_left_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>
  <joint name="${prefix}front_left_wheel_joint" type="continuous">
    <parent link="${prefix}front_left_steering_link"/>
    <child link="${prefix}front_left_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
  </joint>

  <!-- Front Right Steering Link -->
  <link name="${prefix}front_right_steering_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.01"/> <!-- Small mass for steering link -->
      <inertia
        ixx="1e-5" ixy="0.0" ixz="0.0"
        iyy="1e-5" iyz="0.0"
        izz="1e-5"/>
    </inertial>
  </link>
  <joint name="${prefix}front_right_steering_joint" type="revolute">
    <parent link="${prefix}chassis_link"/>
    <child link="${prefix}front_right_steering_link"/>
    <origin xyz="${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="10" velocity="1.0"/>
  </joint>

  <!-- Front Right Wheel -->
  <link name="${prefix}front_right_wheel">
    <collision>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <geometry>
        <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      <mass value="${wheel_mass}"/>
      <inertia
        ixx="0.000270" ixy="0.0" ixz="0.0"
        iyy="0.000270" iyz="0.0"
        izz="0.000426"/>
    </inertial>
  </link>

  <joint name="${prefix}front_right_wheel_joint" type="continuous">
    <parent link="${prefix}front_right_steering_link"/>
    <child link="${prefix}front_right_wheel"/>
    <origin xyz="0 0 0" rpy="0 0 ${PI/2}"/>
    <axis xyz="1 0 0"/>
  </joint>

  </xacro:macro>
</robot>
